name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-plugin:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - name: Validate Plugin with Gradle
        env:
          gradle.publish.key: ${{ env.GRADLE_PUBLISH_KEY }}
          gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew test-projects:kover-badge-plugin:acceptPlugin :plugins:kover-badge-plugin:publishPlugins --validate-only --stacktrace
